version: '3.8'

services:
  redis:
    image: "redis:alpine"
  web:
    build:
      context: .
      dockerfile: chronicler-web.dockerfile
    image: chronicler:web
    depends_on:
      - redis
    ports:
      - 8080:8080
      - 8181:8181
    volumes:
      - type: bind
        source: ./configs/chronicler.json
        target: /opt/chronicler/config.json
      - "./data/:/data"
      - "./downloaded/:/downloads/"
  worker:
    build:
      context: .
      dockerfile: chronicler-worker.dockerfile
    image: chronicler:worker
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./configs/youtube-dl.conf
        target: /etc/youtube-dl.conf
        read_only: true
      - type: bind
        source: ./configs/chronicler.json
        target: /opt/chronicler/config.json
      - "./downloaded/:/downloads/"
      - "./data/:/data"