FROM debian:stable-slim

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=en_US:en

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
        bash \
        ca-certificates \
        ffmpeg \
        git \
        locales \
        locales-all \
        make \
        mplayer \
        mpv \
        pandoc \
        python3 \
        python3-pip \
        rtmpdump \
        zip \
        && pip3 install -U youtube-dl \
    && apt-get remove -y \
        git \
        make \
        pandoc \
        && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workdir

CMD [ "youtube-dl",  "--version"]